### ISSUE TITLE
Move OGNL under a dedicated organisation

### ISSUE THREAD

**Issue by lukaszlenart** [orphan-oss/ognl#141]
I would like to move this project under [Softwaremill](https://github.com/softwaremill/)'s umbrella - we have a large experience in maintaining Open Source projects and supporting [open source projects](https://softwaremill.com/open-source/) is one of our core values :)
At the same time I would like to request ASF to drop [Commons-OGNL](https://commons.apache.org/proper/commons-ognl/) as this is outdated and unsupported project, tbh :(

Any objections @jkuhnert @harawata @JCgH4164838Gh792C124B5 @yasserzamani and others?

**Comment by harawata** [comment]
Thanks for the heads up, @lukaszlenart !
There should be no big impact on MyBatis. No objection from me. 👍

**Comment by lukaszlenart** [comment]
The only impact I see is to use `org.ognl` as a `groupId`

**Comment by harawata** [comment]
As MyBatis uses maven-shade-plugin to includes OGNL in its JAR, the impact of groupId change is relatively small, I believe.

It could cause the classic 'JAR hell' situation to other projects, though.
- Project A depends on library A and B.
- Library A depends on `ognl/ognl`
- Library B depends on `org.ognl/ognl`

You should not trust me on this, but it might be better to change the package name from `ognl` to `org.ognl` if you change the `groupId`.

**Comment by lukaszlenart** [comment]
@harawata thanks a lot, valid point 👍

**Comment by yasserzamani** [comment]
Works for me too, thanks for your support :+1: :)

**Comment by JCgH4164838Gh792C124B5** [comment]
Hi @lukaszlenart , thanks for including us in the discussion.

I do not claim to fully understand what ramifications there might be for the proposed "project move", so please keep that in mind for any of my comments.  :smile:

That being said, if you think it is a good plan for maintaining OGNL in the future, given your continued efforts in maintaining this repository, then it is probably reasonable.  👍  The many thumbs-up in the issue commentary above would seem to indicate that as well.  :wink:

If the `groupId` and/or package names are changed, it could have some build impacts (as @harawata mentioned above).  If the package name changes, there might be some additional "ripple effects" for  some projects/applications built using the current naming (some change impacts are not always easy to predict).

**Comment by lukaszlenart** [comment]
Thanks a lot for all the comments! The `groupId` & package change can be discussed later, if we agree such change is needed. Right I do not expect any large changes. I would like to extract [the benchmark part](https://github.com/apache/commons-ognl/tree/master/src/benchmarks) from Commons-OGNL and moved it here.

**Comment by lukaszlenart** [comment]
As I started large refactoring #155 of OGNL I wonder if moving this code under SML gives any advantage ... I thought about creating another organisation under Github which will take over all orphan projects like this one.

**Comment by jkuhnert** [comment]
Sorry @lukaszlenart I didn't notice this until now. Absolutely agree, you are clearly the maintainer of project now so happy to do whatever you want. I only stuck this in github originally when Patrick was closing down opensymphony or whatever the last home was called.

**Comment by lukaszlenart** [comment]
@jkuhnert thanks a lot, I created a new Github organisation to cover all OSS projects I'm maintaining right now and I think it will be a better place for OGNL - could you transfer this repo under Orphan OSS?

https://github.com/orphan-oss
https://orphan.software/
