### ISSUE TITLE
如何解决安全问题。How ognl solve safety problem

### ISSUE THREAD

**Issue by LY1806620741** [orphan-oss/ognl#161]
我在使用的时候发现ognl的权限很大，我希望的是他仅能操作put进上下文的类及子类和java.lang类。When I use it, I find that ognl has great permissions. What I hope is that it can only operate classes and subclasses of put into context and `java.lang` classes

**Comment by LY1806620741** [comment]
我通过重写AbstractMemberAccess实现了这个方式，但为什么不集成在包里呢。I achieved this by rewriting abstractmemberaccess, but why not integrate it into the package

**Comment by LY1806620741** [comment]
可以看到有黑名单，但是我无法增加或者删除条目[link](https://github.com/jkuhnert/ognl/blob/a8f237149daf544592fbb60f553642b015a1057f/src/main/java/ognl/OgnlRuntime.java#L1144),是否可以对不同的应用场景增加不同的特性呢。You can see that there are blacklists [link](https://github.com/jkuhnert/ognl/blob/a8f237149daf544592fbb60f553642b015a1057f/src/main/java/ognl/OgnlRuntime.java#L1144), but I can't add or delete entries. Can I add different features to different application scenarios

**Comment by lukaszlenart** [comment]
Not sure if I understood your question but you can implement [MemberAccess](https://github.com/jkuhnert/ognl/blob/master/docs/DeveloperGuide.md#member-access) and have a full control depending on your needs. OGNL is used in different scenarios and such approach allows adjusts its behaviour to given projects' needs, like it was done in Apache Struts for example.

**Comment by LY1806620741** [comment]
使用 [MemberAccess](https://github.com/jkuhnert/ognl/blob/master/docs/DeveloperGuide.md#member-access) 确实让用户可以更灵活的控制。但没有提供一些有效的安全解决方案我认为是一种懒政，相当于说嗨这个问题我抛给你了，因此提几点建议。Use [memberaccess]（ https://github.com/jkuhnert/ognl/blob/master/docs/DeveloperGuide.md#member -Access) does allow users to control more flexibly. But I think it's a lazy policy not to provide some effective security solutions, which is equivalent to saying hey, I threw this problem to you, so I put forward some suggestions.

我的使用场景是只允许ognl操作有限的类，我是这么做的: My usage scenario is to allow only classes with limited ognl operations, which is what I do:
1. 可以增加字节码扫描，只允许安全的set/get方法, 不允许对外调用.Bytecode scanning can be added. Only safe set/get methods are allowed, and external calls are not allowed
2. 可以增加方法白名单和黑名单来控制.You can add methods white list and blacklist to control
3. 可以增加对象操作空间，即ognl只能操作受上下文管理的类.You can increase the object operation space, that is, ognl can only operate on classes under context management.

**Comment by lukaszlenart** [comment]
What you suggest is already implemented using JVM SecurityManager and also in sandbox, check this PR #69
