### ISSUE TITLE
Most unit tests no longer running?

### ISSUE THREAD

**Issue by petergeneric** [orphan-oss/ognl#213]
I spotted a difference between unit tests run in my IDE and at the commandline, where in the IDE a large number of tests are now failing - I think these are genuine failures, and aren't being picked up in mvn because the majority of the unit tests are no longer being run on a `mvn test`.

Example, using an older commit:
```
git checkout abec9c287d32f9af16cf2cbdac8e9372cd6c1ea7
mvn clean test

...
[INFO] Tests run: 940, Failures: 0, Errors: 0, Skipped: 0
```

But:
```
git checkout master
mvn clean test

...
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0
```

Whereas when I run all master branch tests in IntelliJ IDEA (using 'Run All Tests'), I'm seeing `Tests failed: 431, passed: 517 of 948 tests - 5 sec 890 ms`

**Comment by petergeneric** [comment]
git bisect indicates the problem was introduced in commit 79e8f21369c810d3729636dfde3b1e0bdbb948b2, I think it may be the addition of the junit `5.x` dependency in that commit causing surefire to no longer run junit `4.x` tests

**Comment by lukaszlenart** [comment]
Great, thanks for finding this - already addressed most of the issues, just NullHandlerTest left :)
