### ISSUE TITLE
Cannot call static method through interface?

### ISSUE THREAD

**Issue by hengyunabc** [orphan-oss/ognl#221]
```java
public interface III {

    public static String staticMethod() {
        return "iii";
    }

}
```

```java
import java.lang.reflect.Method;
import java.util.List;

import ognl.Ognl;
import ognl.OgnlException;
import ognl.OgnlRuntime;

public class TestIII implements III {

    public static void main(String[] args) throws OgnlException {

        System.err.println(III.staticMethod()); // ok

        List<Method> methods = OgnlRuntime.getMethods(III.class, "staticMethod", true);

        System.err.println(methods); // ok

        System.err.println(Ognl.getValue("@III@class", "")); // ok

        System.err.println(Ognl.getValue("@System@getProperties()", "")); // ok

        System.err.println(Ognl.getValue("@TestIII@staticMethod()", "")); // ok

        System.err.println(Ognl.getValue("@III@staticMethod()", "")); // error
    }

}

```

Error:

```
Exception in thread "main" ognl.OgnlException: No method accessor for interface III
```

**Comment by lukaszlenart** [comment]
Default methods aren't static, you must access them through an instance. I added an [example](https://github.com/orphan-oss/ognl/blob/master/src/test/java/ognl/test/Java8Test.java#L37-L42) how to do it.

**Comment by hengyunabc** [comment]
@lukaszlenart Thank you for your reply. The example above does not invoke the default method; it calls a static method of an interface. It can be called directly without creating an object.

```java
System.err.println(III.staticMethod()); // ok
```

**Comment by lukaszlenart** [comment]
Ah... right :D Yet I added another example and it works, see [this](https://github.com/orphan-oss/ognl/blob/master/src/test/java/ognl/test/StaticsAndConstructorsTest.java#L51) test and the [interface](https://github.com/orphan-oss/ognl/blob/master/src/test/java/ognl/test/objects/StaticInterface.java)

**Comment by hengyunabc** [comment]
@lukaszlenart Thanks.

It seems that using `Ognl.compileExpression` works correctly, using `Ognl.parseExpression` error.

```java
        OgnlContext context = Ognl.createDefaultContext(null, new DefaultMemberAccess(false));
        Root root = new Root();
        context.setRoot(new Object());

        Object parseExpression = Ognl.parseExpression("@ognl.test.objects.StaticInterface@staticMethod()");

        Node compileExpression = Ognl.compileExpression(context, root,
                "@ognl.test.objects.StaticInterface@staticMethod()");

        // ok
        System.out.println(Ognl.getValue(compileExpression, context, root)); // or
        // error
        System.out.println(Ognl.getValue(parseExpression, context)); //error
```

output:

```
static
Exception in thread "main" ognl.OgnlException: No method accessor for interface ognl.test.objects.StaticInterface
```

**Comment by lukaszlenart** [comment]
I'm not sure if I understand the problem - `parseExpression` is rather used to _validate_ the expression, it isn't used to _compile_ the expression into an _executable_ form

**Comment by hengyunabc** [comment]
Sorry, maybe I didn't explain the situation clearly. I'll try my best to clarify.

Initially, I thought the following invocation would succeed:

```java
        OgnlContext context = Ognl.createDefaultContext(null, new DefaultMemberAccess(false));
        Root root = new Root();
        context.setRoot(new Object());
        
        // javadoc: Convenience method that combines calls to parseExpression and getValue.
        Ognl.getValue("@ognl.test.objects.StaticInterface@staticMethod()", root); // error
```

However, it fails.

Based on the specific code execution process, I found that it is:

1. Calling `Ognl.parseExpression("@ognl.test.objects.StaticInterface@staticMethod()");`,
1. Then calling `Ognl.getValue(parseExpression, context)`.

______________________________________________________________________

In the example you provided: https://github.com/orphan-oss/ognl/blob/master/src/test/java/ognl/test/StaticsAndConstructorsTest.java#L51

It can execute successfully because in the testcase, it explicitly calls `Ognl.compileExpression`

- https://github.com/orphan-oss/ognl/blob/master/src/test/java/ognl/test/OgnlTestCase.java#L114C10-L114C10

```
Ognl.compileExpression(context, root,
                "@ognl.test.objects.StaticInterface@staticMethod()");
```

Then it executes `Ognl.getValue(compileExpression, context, root)`, so it can succeed.

______________________________________________________________________

So, my question is:

- `ognl.Ognl.getValue(String, Object)`, should it be able to execute `Ognl.getValue("@ognl.test.objects.StaticInterface@staticMethod()", root)` successfully?
- Because other expressions can be executed successfully, for example: `Ognl.getValue("@ognl.test.objects.StaticInterface@class", root)`.

**Comment by lukaszlenart** [comment]
`class` is threaten in some special way and from Ognl perspective `class` is a _static field_ which is represented by `ASTSTaticField` class, while `staticMethod()` is a _static method_ represented by `ASTStaticMethod` class - you cannot compare behaviour of those two.

Please also take a look on the `compileExpression` implementation:

```java
    public static Node compileExpression(OgnlContext context, Object root, String expression) throws Exception {
        Node expr = (Node) Ognl.parseExpression(expression);

        OgnlRuntime.compileExpression(context, expr, root);

        return expr;
    }
```

You can notice the expression is parsed in the first step and then compiled. Just parsing the expression isn't enough, it works for `class` because there are _special_ cases to cover such behaviour -> `OgnlRuntime#getStaticField()`

I would say the Ognl behaves properly, _parsed expression isn't compiled_ - it's like Java source code, it should be parsable to be compiled into binary code.

**Comment by hengyunabc** [comment]
@lukaszlenart Thank you very much.
