### ISSUE TITLE
Issue with SecurityManager and 3.0.19

### ISSUE THREAD

**Issue by warlockza** [orphan-oss/ognl#31]
Security Manager still does not work correctly with OGNL. The only workaround appears to be OgnlRuntime.setSecurityManager(null),

We get

java.lang.IllegalAccessException: Method [public java.lang.String com.opensymphony.xwork2.ActionSupport.execute() throws java.lang.Exception] cannot be accessed.

Can you please either fix Ognl's ability to work with security manager , or provide an example working policy file

**Comment by lukaszlenart** [comment]
but this doesn't look like an issue in OGNL but rather in Apache Struts, and what do you mean by "still does not work" - did that happen already?

**Comment by lukaszlenart** [comment]
The same issue as reported [here](https://issues.apache.org/jira/browse/OGNL-256)

**Comment by warlockza** [comment]
Apparently there were various fixes to the earlier 3.0.x versions that were supposed to let it workm but we have never managed to after trying various versions, to get it working ..

**Comment by lukaszlenart** [comment]
Can you provide the whole stacktrace?
