### ISSUE TITLE
This library (3.2.6) vs Apache commons library (4.0)?

### ISSUE THREAD

**Issue by joshka** [orphan-oss/ognl#54]
Hi,
I note that the Apache commons ognl library hasn't had an update in about 2 years, but this library has. Is this just because the 4.0 (commons) lib is seen is super stable and needs no fixes, or is choosing to depend on this library due to the ongoing support / fixes etc. for a new project the right choice?

**Comment by lukaszlenart** [comment]
This library (3.x series) should be treated as outdated but still supported. But in longer perspective I would like to port all the fixes/improvements to the Apache Commons OGNL and used it instead this library. Any backward compatibility will be persisted in matter of functionality (you will have to just use different imports).

So if you want to start a new project you can use this library (3.x series) with a clear path to migrate to 4.x at some point.

**Comment by joshka** [comment]
Thanks,

Is there a list of things that are fixed in 3.x that are not in 4.x?
What about things fixed in 4.x that are not in 3.x?

**Comment by lukaszlenart** [comment]
There is no such list and mainly performance was improved in 4.x

**Comment by peteruhnak** [comment]
> Aug 7, 2018
> This library (3.x series) should be treated as outdated but still supported.

Does this still make sense, considering this (3.x) is actively developed compared to https://github.com/apache/commons-ognl (which is not, and doesn't seem to have to contain a single stable release)?

**Comment by lukaszlenart** [comment]
Yeah... yet I still have hope :)

**Comment by peteruhnak** [comment]
Maybe I am confused about the status of things... does the current state of apache/commons-ognl/4.0.0-SNAPSHOT contain something that is not in the jkuhnert/ognl/3.2?
If not, would it then make more sense to just move everything from here (the development of 3.2 (and 3.1?)) from this repo to that one? (Until it one day reaches 4.0.0 version)
Or am I missing something?

**Comment by lukaszlenart** [comment]
It's complicated ;-)

OGNL 4.0 contains some performance improvements plus some performance tests. But this project is under Apache Commons and I was/am always worried that it will take months to release a new version because of high expectations. It was easier for me to handle changes here and release them when needed.

**Comment by lukaszlenart** [comment]
I took over the OGNL project and I will going to maintain and extend it here
