### ISSUE TITLE
Can ognl support java8 lambda expressions

### ISSUE THREAD

**Issue by timnick-snow** [orphan-oss/ognl#66]
`List<String> list = Arrays.asList("a","b","c","d");
 list.forEach(s -> System.out.println(s));`
but it may cause Exception:
`String expression = "{'a','b','c','d'}.foreach(s -> java.lang.System.out.println(s))";
Ognl.getValue(expression, context, root);
`

**Comment by lukaszlenart** [comment]
I'm not sure if this is the best idea, adding support for such complicated constructs is a bit out of scope and OGNL already has support for [lambda expressions](https://github.com/jkuhnert/ognl/blob/master/docs/LanguageGuide.md#pseudo-lambda-expressions).
